name: CI Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, 'pypy-2.7', 'pypy-3.6', 'pypy-3.7']

    steps:
    - uses: actions/checkout@v3.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
      env:
        DJANGO_SETTINGS_MODULE: django_extra_field_validation.settings
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
